# site settings

title: Saloni Bhartia
description: Fullstack Software Engineer  
taglong: "Software Engineer "
tagshort: ""
url: https://saloniBhartia.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/saloniBhartia/saloniBhartia.github.io

# author settings

author:
  name: Saloni Bhartia
  email: salonibhartia1996@gmail.com
photo: /assets/jpg/photo.jpg

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
